# theme: jekyll-theme-minimal
remote_theme: pages-themes/slate@v0.2.0
logo: /assets/Photo.jpg
title: Maciej Czerniak
description: Bookmark this to keep an eye on my project updates!
show_downloads: false